// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzsiickgzzjxkzdkdozm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6c2lpY2tnenpqeGt6ZGtkb3ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MDA2MjgsImV4cCI6MjA2Nzk3NjYyOH0.xDMFu7k5v641R1YASXA2nwnIA15T9mqbxyKlxGPAGLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});